#!/bin/bash

NAME="$1"
UBUNTU_12_AMI=ami-3d4ff254
NOT_TERMINATED="--filter instance-state-name=running --filter instance-state-name=pending --filter instance-state-name=stopping --filter instance-state-name=stopped --filter instance-state-name=shutting-down"

# Check NAME uniqueness
EC2_DESCRIBE=`ec2-describe-instances --filter tag:Name=$NAME $NOT_TERMINATED`
if [ "$EC2_DESCRIBE" != "" ]; then
  echo "$NAME already exists"
  exit 0
fi

# Create server instance.
EC2_RUN=`ec2run $UBUNTU_12_AMI -k miscproj-ec2 -t t1.micro`
set $EC2_RUN
INSTANCE=$6
RESOURCE=$2

#echo $1 $2 $3 $4 $5 $6

# Set name
EC2_TAG=`ec2addtag $INSTANCE --tag Name=$NAME`

# sleep 2

# Get hostname
EC2_DESCRIBE=`ec2-describe-instances $INSTANCE --filter instance-state-name=pending --filter instance-state-name=running`
set $EC2_DESCRIBE
HOSTNAME=$8

#echo "Instance: $INSTANCE"
#echo "Hostname: $HOSTNAME"

echo $HOSTNAME

#ec2-terminate-instances $INSTANCE

