#!/bin/bash

NAME=
KEY_NAME=$EC2_KEYPAIR
EC2_KEYPAIR=$KEY_NAME;
EC2_PRIVATE_KEY=~/.ec2/pk-$KEY_NAME.pem
EC2_CERT=~/.ec2/cert-$KEY_NAME.pem
UBUNTU_12_AMI=ami-3d4ff254

# Handle arguments
while true; do
  case "$1" in
    -k | --key-name ) 
      KEY_NAME="$2"; 
      EC2_KEYPAIR=$KEY_NAME;
      EC2_PRIVATE_KEY=~/.ec2/pk-$KEY_NAME.pem
      EC2_CERT=~/.ec2/cert-$KEY_NAME.pem
      shift; shift ;;
    -- ) shift; break ;;
    * ) NAME="$1"; break ;;
  esac
done

EC2_DESCRIBE=`ec2-describe-instances --filter tag:Name=$NAME --filter instance-state-name=running`

if [ "$EC2_DESCRIBE" == "" ]; then
  echo "$NAME not found"
  exit 0
fi

set $EC2_DESCRIBE
INSTANCE=$6
HOSTNAME=$8

EC2_TERMINATE=`ec2-terminate-instances $INSTANCE`

set $EC2_TERMINATE

if [ "$INSTANCE" == "$2" ]; then
  echo "$HOSTNAME terminated"
fi

