#!/bin/bash


KEY_NAME=$EC2_KEYPAIR
EC2_KEYPAIR=$KEY_NAME;
EC2_PRIVATE_KEY=~/.ec2/pk-$KEY_NAME.pem
EC2_CERT=~/.ec2/cert-$KEY_NAME.pem
SHOW_HOSTNAMES=false
SHOW_INSTANCE_IDS=false
old=$IFS
IFS='
'

# Handle arguments
while true; do
  case "$1" in
    -k | --key-name ) 
      KEY_NAME="$2"; 
      EC2_KEYPAIR=$KEY_NAME;
      EC2_PRIVATE_KEY=~/.ec2/pk-$KEY_NAME.pem
      EC2_CERT=~/.ec2/cert-$KEY_NAME.pem
      shift; shift ;;
    -i | --instance-ids ) SHOW_INSTANCE_IDS=true; shift ;;
    -h | --hostnames ) SHOW_HOSTNAMES=true; shift ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done

array=`ec2-describe-instances --filter instance-state-name=running --filter instance-state-name=pending --filter instance-state-name=stopping --filter instance-state-name=stopped --filter instance-state-name=shutting-down`

for line in $array; do
  IFS=$old
  set $line
  if [ $SHOW_INSTANCE_IDS == true ]; then
    if [ "$1" == "INSTANCE" ]; then
      echo "ID: $2"
    fi
  fi
  if [ $SHOW_HOSTNAMES == true ]; then
    if [ "$1" == "INSTANCE" ]; then
      echo "Host: $4"
    fi
  fi
  if [[ "$1" == "TAG" && "$4" == "Name" ]]; then
    echo "Name: $5"
  fi
done

IFS=$old

